export { default as SwH1 } from './SwH1.vue'
export { default as SwH2 } from './SwH2.vue'
export { default as SwH3 } from './SwH3.vue'
export { default as SwH4 } from './SwH4.vue'
export { default as SwBody } from './SwBody.vue'
export { default as SwSmall } from './SwSmall.vue'
export { default as SwCaption } from './SwCaption.vue'
